"""Cheap, relaxation-free structural checks for early design triage."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import math


@dataclass(frozen=True)
class PDBAtom:
    chain: str
    residue: int
    name: str
    x: float
    y: float
    z: float


def read_atoms(pdb_path: str | Path) -> list[PDBAtom]:
    atoms: list[PDBAtom] = []
    for line in Path(pdb_path).read_text().splitlines():
        if not line.startswith("ATOM  "):
            continue
        try:
            atoms.append(PDBAtom(line[21], int(line[22:26]), line[12:16].strip(), float(line[30:38]), float(line[38:46]), float(line[46:54])))
        except (IndexError, ValueError):
            continue
    return atoms


def _distance(left: PDBAtom, right: PDBAtom) -> float:
    return math.dist((left.x, left.y, left.z), (right.x, right.y, right.z))


def count_interchain_contacts(
    pdb_path: str | Path,
    target_chain: str = "A",
    binder_chain: str = "B",
    cutoff_angstrom: float = 5.0,
) -> int:
    """Count unique binder residues contacting the target."""
    atoms = read_atoms(pdb_path)
    target = [atom for atom in atoms if atom.chain == target_chain]
    binder = [atom for atom in atoms if atom.chain == binder_chain]
    contacting = {atom.residue for atom in binder if any(_distance(atom, other) <= cutoff_angstrom for other in target)}
    return len(contacting)


def count_heavy_atom_clashes(pdb_path: str | Path, cutoff_angstrom: float = 2.4) -> int:
    """Count close non-bonded atom pairs as a coarse clash signal."""
    atoms = [atom for atom in read_atoms(pdb_path) if atom.name != "H"]
    clashes = 0
    for index, left in enumerate(atoms):
        for right in atoms[index + 1:]:
            if left.chain == right.chain and abs(left.residue - right.residue) <= 1:
                continue
            if _distance(left, right) < cutoff_angstrom:
                clashes += 1
    return clashes


def early_structure_report(
    pdb_path: str | Path,
    target_chain: str = "A",
    binder_chain: str = "B",
    minimum_contacts: int = 7,
) -> dict[str, int | bool | str]:
    """Return checks suitable for pre-MPNN or pre-relaxation filtering."""
    contacts = count_interchain_contacts(pdb_path, target_chain, binder_chain)
    clashes = count_heavy_atom_clashes(pdb_path)
    return {
        "pdb": str(pdb_path),
        "interchain_contact_residues": contacts,
        "heavy_atom_clashes": clashes,
        "passes_contacts": contacts >= minimum_contacts,
        "passes_clashes": clashes == 0,
        "passes_early_check": contacts >= minimum_contacts and clashes == 0,
    }


def aligned_binder_rmsd(
    reference_pdb: str | Path,
    predicted_pdb: str | Path,
    target_chain: str = "A",
    binder_chain: str = "B",
) -> float | None:
    """Align predicted and reference targets, then calculate binder CA RMSD.

    The reference should be the initial complex generated by ColabFold/
    BindCraft. The predicted structure is typically an ESMFold complex. Both
    structures must use compatible residue numbering and chain identifiers.
    ``None`` means too few shared CA atoms were available for a meaningful fit.
    """
    try:
        import numpy as np
    except ImportError as exc:
        raise RuntimeError("numpy is required for aligned RMSD calculation") from exc

    reference_atoms = read_atoms(reference_pdb)
    predicted_atoms = read_atoms(predicted_pdb)

    def ca_map(atoms: list[PDBAtom], chain: str) -> dict[int, PDBAtom]:
        return {atom.residue: atom for atom in atoms if atom.chain == chain and atom.name == "CA"}

    reference_target = ca_map(reference_atoms, target_chain)
    predicted_target = ca_map(predicted_atoms, target_chain)
    shared_target = sorted(set(reference_target) & set(predicted_target))
    if len(shared_target) < 3:
        return None

    reference_points = np.array([[reference_target[index].x, reference_target[index].y, reference_target[index].z] for index in shared_target], dtype=float)
    predicted_points = np.array([[predicted_target[index].x, predicted_target[index].y, predicted_target[index].z] for index in shared_target], dtype=float)
    reference_center = reference_points.mean(axis=0)
    predicted_center = predicted_points.mean(axis=0)
    covariance = (predicted_points - predicted_center).T @ (reference_points - reference_center)
    left, _, right_transpose = np.linalg.svd(covariance)
    rotation = left @ right_transpose
    if np.linalg.det(rotation) < 0:
        left[:, -1] *= -1
        rotation = left @ right_transpose
    translation = reference_center - predicted_center @ rotation

    reference_binder = ca_map(reference_atoms, binder_chain)
    predicted_binder = ca_map(predicted_atoms, binder_chain)
    shared_binder = sorted(set(reference_binder) & set(predicted_binder))
    if not shared_binder:
        return None
    reference_binder_points = np.array([[reference_binder[index].x, reference_binder[index].y, reference_binder[index].z] for index in shared_binder], dtype=float)
    predicted_binder_points = np.array([[predicted_binder[index].x, predicted_binder[index].y, predicted_binder[index].z] for index in shared_binder], dtype=float)
    aligned_binder = predicted_binder_points @ rotation + translation
    return round(float(np.sqrt(np.mean(np.sum((aligned_binder - reference_binder_points) ** 2, axis=1)))), 3)


def aligned_complex_rmsd(
    reference_pdb: str | Path,
    predicted_pdb: str | Path,
    target_chain: str = "A",
    binder_chain: str = "B",
) -> float | None:
    """Align on the target chain and calculate CA RMSD for both chains.

    This is the whole-complex counterpart to :func:`aligned_binder_rmsd`.
    The target fit is not included in the RMSD selection unless it has shared
    CA residues; its coordinates are included in the final complex RMSD.
    """
    try:
        import numpy as np
    except ImportError as exc:
        raise RuntimeError("numpy is required for aligned RMSD calculation") from exc

    reference_atoms = read_atoms(reference_pdb)
    predicted_atoms = read_atoms(predicted_pdb)

    def ca_map(atoms: list[PDBAtom], chain: str) -> dict[int, PDBAtom]:
        return {atom.residue: atom for atom in atoms if atom.chain == chain and atom.name == "CA"}

    reference_target = ca_map(reference_atoms, target_chain)
    predicted_target = ca_map(predicted_atoms, target_chain)
    shared_target = sorted(set(reference_target) & set(predicted_target))
    if len(shared_target) < 3:
        return None

    reference_points = np.array([[reference_target[index].x, reference_target[index].y, reference_target[index].z] for index in shared_target], dtype=float)
    predicted_points = np.array([[predicted_target[index].x, predicted_target[index].y, predicted_target[index].z] for index in shared_target], dtype=float)
    reference_center = reference_points.mean(axis=0)
    predicted_center = predicted_points.mean(axis=0)
    covariance = (predicted_points - predicted_center).T @ (reference_points - reference_center)
    left, _, right_transpose = np.linalg.svd(covariance)
    rotation = left @ right_transpose
    if np.linalg.det(rotation) < 0:
        left[:, -1] *= -1
        rotation = left @ right_transpose
    translation = reference_center - predicted_center @ rotation

    reference_all = {(atom.chain, atom.residue): atom for atom in reference_atoms if atom.name == "CA"}
    predicted_all = {(atom.chain, atom.residue): atom for atom in predicted_atoms if atom.name == "CA"}
    shared_all = sorted(set(reference_all) & set(predicted_all))
    if not shared_all:
        return None
    reference_ca = np.array([[reference_all[key].x, reference_all[key].y, reference_all[key].z] for key in shared_all], dtype=float)
    predicted_ca = np.array([[predicted_all[key].x, predicted_all[key].y, predicted_all[key].z] for key in shared_all], dtype=float)
    aligned_ca = predicted_ca @ rotation + translation
    return round(float(np.sqrt(np.mean(np.sum((aligned_ca - reference_ca) ** 2, axis=1)))), 3)
